# Generated by Django 4.1.2 on 2022-10-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_is_approved',
            field=models.BooleanField(default=True, help_text=' Approve the album if its name is not explicit'),
        ),
    ]
