# Generated by Django 4.1.2 on 2022-11-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_album_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='creation_time',
            field=models.DateTimeField(unique=True, verbose_name='time created'),
        ),
    ]
