# Generated by Django 4.1.2 on 2022-10-19 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stage_Name', models.CharField(max_length=100, unique=True)),
                ('Social_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_Name', models.CharField(default='New Album', max_length=200, verbose_name='New Album')),
                ('creation_Time', models.DateTimeField(unique=True, verbose_name='time created')),
                ('release_Time', models.DateTimeField(verbose_name='publish time')),
                ('album_Cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('artist_Fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artist')),
            ],
        ),
    ]
